"""empty message

Revision ID: 135c1ed235e4
Revises: 
Create Date: 2023-04-03 23:28:38.567876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135c1ed235e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('temperament', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('zipcode', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('playdates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('chip_number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(precision=2), nullable=False),
    sa.Column('neutered_or_spayed', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chip_number')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('playdate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playdate_id'], ['playdates.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_dogs_playdates',
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('playdates_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['playdates_id'], ['playdates.id'], )
    )
    op.create_table('pd_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sender'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['target'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog_breed',
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('dog_id', 'breed_id')
    )
    op.create_table('owner_dogs',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'dog_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_dogs')
    op.drop_table('dog_breed')
    op.drop_table('pd_request')
    op.drop_table('owner_dogs_playdates')
    op.drop_table('message')
    op.drop_table('dogs')
    op.drop_table('playdates')
    op.drop_table('owner')
    op.drop_table('breeds')
    # ### end Alembic commands ###
